[colors]
text = "#cdd6f4"
subtext0 = "#a6adc8"
overlay0 = "#585b70"
blue = "#89b4fa"
yellow = "#f9e2af"
surface1 = "#45475a"
surface0 = "#313244"
mantle = "#181825"
crust = "#11111b"
lavender = "#b4befe"
green = "#a6e3a1"

[ui]
text = "text"
text_dim = "subtext0"
text_muted = "overlay0"
accent = "blue"
warm = "yellow"
border = "crust"
selection = "surface0"
popup_bg = "mantle"
popup_border = "lavender"
normal_bg = "blue"
insert_bg = "green"
status_fg = "crust"
