[colors]
text = "#c6d0f5"
subtext0 = "#a5adce"
overlay0 = "#626880"
blue = "#8caaee"
yellow = "#e5c890"
surface1 = "#414559"
surface0 = "#303446"
mantle = "#292c3c"
crust = "#232634"
lavender = "#babbf1"
green = "#a6d189"

[ui]
text = "text"
text_dim = "subtext0"
text_muted = "overlay0"
accent = "blue"
warm = "yellow"
border = "crust"
selection = "surface0"
popup_bg = "mantle"
popup_border = "lavender"
normal_bg = "blue"
insert_bg = "green"
status_fg = "crust"
